### ISSUE TITLE
Suggestion for README

### ISSUE THREAD

**Issue by rnemec** [asvetliakov/run-current-test#1]
Alexey,

I love your plugin and hope you are proud of it.
There is not much to add to the functionality, but:

I'd suggest to add in the README document, for the test commands, setting this: `NODE_ENV=test`
E.g. for node.js, mocha, Mac OS X the mocha command would be `NODE_ENV=test mocha ${relativeTestPath} .... --watch`

Note that in most Node setups, dev environment is the default and the tests may by mistake write (or delete) data in the dev database. Also, note the `--watch` - I find it useful when working on particular area.

Eventually, the setting of the environment may be done by the plugin's code.

**Comment by asvetliakov** [comment]
Thanks for suggestion! Just checked and there is no API to set environment when creating integrated terminal instance in vscode (It's possible when spawning command and creating output channel instead, but running command in terminal is much better).

I'm usually setting environment in ```testSetup.js``` file and specifying it when running tests (```-r``` flag for mocha, ```setupTestFrameworkScriptFile``` for jest), this way it's crossplatform and works equally for windows/macos/linux.

I'll add note for specifying NODE_ENV anyway
