### ISSUE TITLE
missing testFileName variable

### ISSUE THREAD

**Issue by wysher** [asvetliakov/run-current-test#4]
with new jest `--runTestsByPath` not works, but you can use file name to determine which file should be considered. 

for Windows it would looks like:

`"jest ${testFileName} --testNamePattern \"${fullTestName}\""`
which will result e.g.: `"jest Modal.test.jsx --testNamePattern "Modal\should render properly""`

PS. I know there's --findRelatedTests parameter, but it takes ages to start.

**Comment by asvetliakov** [comment]
Just published 0.2.0 version which should help with jest on Windows, use ```--testPathPattern``` along with ```${relativeTestPath}``` and make sure you won't set ```unixPaths``` extension settings to false.
